/* Generated by Cython 3.1.6 */

#ifndef __PYX_HAVE__cupy___core__numpy_allocator
#define __PYX_HAVE__cupy___core__numpy_allocator

#include "Python.h"

#ifndef __PYX_HAVE_API__cupy___core__numpy_allocator

#ifdef CYTHON_EXTERN_C
    #undef __PYX_EXTERN_C
    #define __PYX_EXTERN_C CYTHON_EXTERN_C
#elif defined(__PYX_EXTERN_C)
    #ifdef _MSC_VER
    #pragma message ("Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.")
    #else
    #warning Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.
    #endif
#else
    #define __PYX_EXTERN_C extern "C++"
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C void *_calloc(size_t, size_t);
__PYX_EXTERN_C void *_malloc(size_t);
__PYX_EXTERN_C void *_realloc(void *, size_t);
__PYX_EXTERN_C void _free(void *);

#endif /* !__PYX_HAVE_API__cupy___core__numpy_allocator */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

/* WARNING: Use PyImport_AppendInittab("numpy_allocator", PyInit_numpy_allocator) instead of calling PyInit_numpy_allocator directly from Python 3.5 */
PyMODINIT_FUNC PyInit_numpy_allocator(void);

#if PY_VERSION_HEX >= 0x03050000 && (defined(__GNUC__) || defined(__clang__) || defined(_MSC_VER) || (defined(__cplusplus) && __cplusplus >= 201402L))
#if defined(__cplusplus) && __cplusplus >= 201402L
[[deprecated("Use PyImport_AppendInittab(\"numpy_allocator\", PyInit_numpy_allocator) instead of calling PyInit_numpy_allocator directly.")]] inline
#elif defined(__GNUC__) || defined(__clang__)
__attribute__ ((__deprecated__("Use PyImport_AppendInittab(\"numpy_allocator\", PyInit_numpy_allocator) instead of calling PyInit_numpy_allocator directly."), __unused__)) __inline__
#elif defined(_MSC_VER)
__declspec(deprecated("Use PyImport_AppendInittab(\"numpy_allocator\", PyInit_numpy_allocator) instead of calling PyInit_numpy_allocator directly.")) __inline
#endif
static PyObject* __PYX_WARN_IF_PyInit_numpy_allocator_INIT_CALLED(PyObject* res) {
  return res;
}
#define PyInit_numpy_allocator() __PYX_WARN_IF_PyInit_numpy_allocator_INIT_CALLED(PyInit_numpy_allocator())
#endif

#endif /* !__PYX_HAVE__cupy___core__numpy_allocator */
