/* Generated by Cython 3.1.6 */

#ifndef __PYX_HAVE__cupy__cuda__thrust
#define __PYX_HAVE__cupy__cuda__thrust

#include "Python.h"

#ifndef __PYX_HAVE_API__cupy__cuda__thrust

#ifdef CYTHON_EXTERN_C
    #undef __PYX_EXTERN_C
    #define __PYX_EXTERN_C CYTHON_EXTERN_C
#elif defined(__PYX_EXTERN_C)
    #ifdef _MSC_VER
    #pragma message ("Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.")
    #else
    #warning Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.
    #endif
#else
    #define __PYX_EXTERN_C extern "C++"
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C char *cupy_malloc(void *, size_t);
__PYX_EXTERN_C int cupy_free(void *, char *);

#endif /* !__PYX_HAVE_API__cupy__cuda__thrust */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

/* WARNING: Use PyImport_AppendInittab("thrust", PyInit_thrust) instead of calling PyInit_thrust directly from Python 3.5 */
PyMODINIT_FUNC PyInit_thrust(void);

#if PY_VERSION_HEX >= 0x03050000 && (defined(__GNUC__) || defined(__clang__) || defined(_MSC_VER) || (defined(__cplusplus) && __cplusplus >= 201402L))
#if defined(__cplusplus) && __cplusplus >= 201402L
[[deprecated("Use PyImport_AppendInittab(\"thrust\", PyInit_thrust) instead of calling PyInit_thrust directly.")]] inline
#elif defined(__GNUC__) || defined(__clang__)
__attribute__ ((__deprecated__("Use PyImport_AppendInittab(\"thrust\", PyInit_thrust) instead of calling PyInit_thrust directly."), __unused__)) __inline__
#elif defined(_MSC_VER)
__declspec(deprecated("Use PyImport_AppendInittab(\"thrust\", PyInit_thrust) instead of calling PyInit_thrust directly.")) __inline
#endif
static PyObject* __PYX_WARN_IF_PyInit_thrust_INIT_CALLED(PyObject* res) {
  return res;
}
#define PyInit_thrust() __PYX_WARN_IF_PyInit_thrust_INIT_CALLED(PyInit_thrust())
#endif

#endif /* !__PYX_HAVE__cupy__cuda__thrust */
